### ISSUE TITLE
Error compiling sample codes

### ISSUE THREAD

**Issue by BrotherV** [PacktPublishing/TinyML-Cookbook#8]
I have tried to use the [https://github.com/tensorflow/tflite-micro/tree/main](url), but it seems it doesn't have these files.

micro_error_reporter.h
version.h

It is not possible to follow up on the book since the library was recently removed from Library Manager at the request of the TensorFlow Lite Micro maintainers. In addition, you have not mentioned how to install this library in the book.

**Comment by HipsterBrown** [comment]
I ran into this as well and figured out the library has moved to https://github.com/tensorflow/tflite-micro-arduino-examples/tree/main?tab=readme-ov-file#how-to-install. 

Using the updated library also requires changing some of the `#includes` and code.

In the `09_classification.io`:

```diff
#include <TensorFlowLite.h>
#include <tensorflow/lite/micro/all_ops_resolver.h>
#include <tensorflow/lite/micro/micro_mutable_op_resolver.h>
-#include <tensorflow/lite/micro/micro_error_reporter.h>
+#include <tensorflow/lite/micro/tflite_bridge/micro_error_reporter.h>
#include <tensorflow/lite/micro/micro_interpreter.h>
#include <tensorflow/lite/schema/schema_generated.h>
-#include <tensorflow/lite/version.h>
```

```diff
+tflu_interpreter = new tflite::MicroInterpreter(tflu_model, tflu_ops_resolver, tensor_arena, tensor_arena_size);
-tflu_interpreter = new tflite::MicroInterpreter(tflu_model, tflu_ops_resolver, tensor_arena, tensor_arena_size, &tflu_error); 
```

The first compile will take a minute since there's no pre-compiled versions of TFLu for cortex-m4 available from the library.

**Comment by BrotherV** [comment]
@HipsterBrown Thanks Nick, I appreciate it. You saved my day.
